return {

    ["Accessory"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(0, 0),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["AccessoryDescription"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(128, 96),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["Accoutrement"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["Actor"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(16, 0),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["AdGui"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(32, 0),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["AdPortal"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(48, 0),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["AdService"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(64, 160),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["AdvancedDragger"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["AirController"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(64, 0),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["AlignOrientation"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(80, 0),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["AlignPosition"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(96, 0),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["AnalyticsService"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(64, 160),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["AngularVelocity"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(112, 0),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["Animation"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(128, 0),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["AnimationClip"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["AnimationClipProvider"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["AnimationConstraint"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(144, 0),
        ImageRectSize = Vector2.new(16, 15),
    },

    ["AnimationController"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(160, 0),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["AnimationFromVideoCreatorService"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(176, 0),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["AnimationGraphDefinition"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["AnimationNode"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["AnimationNodeDefinition"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["AnimationRigData"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["AnimationTrack"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["Animator"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(192, 0),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["Annotation"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["ArcHandles"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 0),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["AssetDeliveryProxy"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["AssetPatchSettings"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["AssetService"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(64, 160),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["Atmosphere"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(224, 0),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["AtmosphereSensor"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["Attachment"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(240, 0),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["AudioAnalyzer"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(256, 0),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["AudioChannelMixer"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(0, 16),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["AudioChannelSplitter"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(16, 16),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["AudioChorus"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(32, 16),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["AudioCompressor"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(48, 16),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["AudioDeviceInput"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(64, 16),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["AudioDeviceOutput"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(80, 16),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["AudioDistortion"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(96, 16),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["AudioEcho"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(112, 16),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["AudioEmitter"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(128, 16),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["AudioEqualizer"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(144, 16),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["AudioFader"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(160, 16),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["AudioFilter"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(176, 16),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["AudioFlanger"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(192, 16),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["AudioGate"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 16),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["AudioLimiter"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(224, 16),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["AudioListener"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(240, 16),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["AudioPages"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["AudioPitchShifter"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(256, 16),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["AudioPlayer"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(0, 32),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["AudioRecorder"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(16, 32),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["AudioReverb"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(32, 32),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["AudioSearchParams"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["AudioSpeechToText"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(48, 32),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["AudioTextToSpeech"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(64, 32),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["AudioTremolo"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(80, 32),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["AudioWindSynthesizer"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["AuroraScriptService"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(64, 160),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["AvatarCreationService"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(64, 160),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["AvatarEditorService"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(96, 32),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["Backpack"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(112, 32),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["BackpackItem"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["BadgeService"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(64, 160),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["BallSocketConstraint"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(128, 32),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["BanHistoryPages"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["BaseCoreGuiConfiguration"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["BasePart"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["BasePlayerGui"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["BaseRemoteEvent"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["BaseScript"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["BaseWrap"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["Beam"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(144, 32),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["BevelMesh"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["BillboardGui"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(160, 32),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["BinaryStringValue"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(160, 224),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["BindableEvent"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(176, 32),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["BindableFunction"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(192, 32),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["BlockMesh"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 32),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["BloomEffect"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(224, 32),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["BlurEffect"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(240, 32),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["BodyAngularVelocity"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(256, 32),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["BodyColors"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(0, 48),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["BodyForce"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(16, 48),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["BodyGyro"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(32, 48),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["BodyMover"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["BodyPartDescription"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(128, 96),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["BodyPosition"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(48, 48),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["BodyThrust"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(64, 48),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["BodyVelocity"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(80, 48),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["Bone"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(96, 48),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["BoolValue"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(112, 48),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["BoxHandleAdornment"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(128, 48),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["BrickColorValue"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(144, 48),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["BrowserService"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(64, 160),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["BubbleChatConfiguration"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(160, 48),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["BubbleChatMessageProperties"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["BuoyancySensor"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["CFrameValue"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(176, 48),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["CacheableContentProvider"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["Camera"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(192, 48),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["CanvasGroup"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 48),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["Capture"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["CaptureService"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(64, 160),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["CapturesPages"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["CapturesViewConfiguration"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["CatalogPages"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["ChangeHistoryService"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(64, 160),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["ChannelTabsConfiguration"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(224, 48),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["CharacterAppearance"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["CharacterMesh"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(240, 48),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["Chat"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(256, 48),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["ChatInputBarConfiguration"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(0, 64),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["ChatWindowConfiguration"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(16, 64),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["ChatWindowMessageProperties"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["ChorusSoundEffect"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(32, 64),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["ClickDetector"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(48, 64),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["ClientReplicator"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(64, 64),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["ClimbController"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(80, 64),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["Clothing"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["Clouds"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(96, 64),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["ClusterPacketCache"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["CollectionService"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(64, 160),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["Color3Value"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(160, 224),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["ColorCorrectionEffect"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(112, 64),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["ColorGradingEffect"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["CommerceService"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(64, 160),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["CompositeValueCurve"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["CompressorSoundEffect"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(128, 64),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["ConeHandleAdornment"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(144, 64),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["ConfigService"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(64, 160),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["ConfigSnapshot"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["Configuration"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(160, 64),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["ConfigureServerService"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(64, 160),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["Constraint"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["ContentProvider"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["ContextActionService"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(64, 160),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["Controller"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(176, 64),
        ImageRectSize = Vector2.new(16, 12),
    },

    ["ControllerBase"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["ControllerManager"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["ControllerPartSensor"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["ControllerSensor"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["ControllerService"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(64, 160),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["CookiesService"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(64, 160),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["CoreGuiConfiguration"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["CornerWedgePart"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(192, 64),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["CreatorStoreService"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(64, 160),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["CurveAnimation"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["CustomEvent"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["CustomEventReceiver"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["CylinderHandleAdornment"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 64),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["CylinderMesh"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["CylindricalConstraint"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(224, 64),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["DataModel"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["DataModelMesh"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["DataModelSession"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["DataStore"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["DataStoreGetOptions"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["DataStoreIncrementOptions"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["DataStoreInfo"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["DataStoreKey"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["DataStoreKeyInfo"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["DataStoreKeyPages"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["DataStoreListingPages"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["DataStoreObjectVersionInfo"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["DataStoreOptions"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["DataStorePages"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["DataStoreService"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(64, 160),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["DataStoreSetOptions"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["DataStoreVersionPages"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["Debris"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["Decal"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(240, 64),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["DepthOfFieldEffect"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(256, 64),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["Dialog"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(0, 80),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["DialogChoice"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(16, 80),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["DigitsRigDescription"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(128, 96),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["DistortionSoundEffect"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(32, 80),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["DoubleConstrainedValue"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(160, 224),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["DragDetector"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(48, 80),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["Dragger"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["DynamicRotate"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["EchoSoundEffect"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(64, 80),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["EditableImage"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(80, 80),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["EditableMesh"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(96, 80),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["EncodingService"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(64, 160),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["EqualizerSoundEffect"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(112, 80),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["EulerRotationCurve"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["ExperienceInviteOptions"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["ExperienceNotificationService"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(64, 160),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["Explosion"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(128, 80),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["FaceControls"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(144, 80),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["FaceInstance"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["Feature"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["FeatureRestrictionManager"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["File"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(160, 80),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["FileMesh"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["Fire"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(176, 80),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["Flag"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["FlagStand"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["FlagStandService"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(64, 160),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["FlangeSoundEffect"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(192, 80),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["FloatCurve"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["FloorWire"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["FluidForceSensor"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["Folder"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 80),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["ForceField"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(224, 80),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["FormFactorPart"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["Frame"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(240, 80),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["FriendPages"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["FriendService"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(64, 160),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["FunctionalTest"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["GamePassService"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(64, 160),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["GamepadService"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(64, 160),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["GeneratedFolder"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(256, 80),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["GenerationService"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(64, 160),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["GenericChallengeService"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(64, 160),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["Geometry"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["GeometryService"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(64, 160),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["GetTextBoundsParams"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["GlobalDataStore"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["Glue"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["GroundController"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(0, 96),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["GroupService"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(64, 160),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["GuiBase"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["GuiBase2d"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["GuiBase3d"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["GuiButton"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["GuiLabel"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["GuiMain"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["GuiObject"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["GuiService"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(64, 160),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["GuidRegistryService"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(64, 160),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["HSRDataContentProvider"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["HandleAdornment"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["Handles"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(16, 96),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["HandlesBase"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["HapticEffect"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(32, 96),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["HapticService"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(48, 96),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["Hat"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["HeapProfilerService"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(64, 160),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["HeightmapImporterService"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(64, 96),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["HiddenSurfaceRemovalAsset"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["Highlight"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(80, 96),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["HingeConstraint"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(96, 96),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["Hint"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["Hole"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["Hopper"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["HopperBin"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["HttpRbxApiService"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(64, 160),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["HttpService"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(64, 160),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["Humanoid"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(112, 96),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["HumanoidController"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["HumanoidDescription"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(128, 96),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["HumanoidRigDescription"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(128, 96),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["IKControl"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(144, 96),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["ILegacyStudioBridge"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["ImageButton"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(160, 96),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["ImageHandleAdornment"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(176, 96),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["ImageLabel"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(192, 96),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["IncrementalPatchBuilder"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["InputAction"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 96),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["InputActionLabel"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(224, 96),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["InputBinding"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(240, 96),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["InputContext"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(256, 96),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["InputObject"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["InsertService"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(64, 160),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["Instance"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["InstanceAdornment"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["InstanceExtensionsService"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(64, 160),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["IntConstrainedValue"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(160, 224),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["IntValue"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(160, 224),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["IntersectOperation"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(0, 112),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["InventoryPages"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["JointInstance"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["JointsService"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(64, 160),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["KeyboardService"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(64, 160),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["Keyframe"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["KeyframeMarker"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["KeyframeSequence"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["KeyframeSequenceProvider"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["LayerCollector"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["Light"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["Lighting"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(16, 112),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["LineForce"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(32, 112),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["LineHandleAdornment"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(48, 112),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["LinearVelocity"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(64, 112),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["LocalScript"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(80, 112),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["LocalizationService"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(96, 112),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["LocalizationTable"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(112, 112),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["LogService"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(64, 160),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["Logger"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["LoginService"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(64, 160),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["LuaSourceContainer"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["LuaWebService"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(64, 160),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["MLService"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(64, 160),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["MLSession"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["MakeupDescription"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(128, 96),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["ManualGlue"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["ManualSurfaceJointInstance"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["ManualWeld"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["MarkerCurve"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["MarketplaceService"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(64, 160),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["MatchmakingService"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(64, 160),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["MaterialService"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(128, 112),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["MaterialVariant"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(144, 112),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["MemStorageConnection"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["MemStorageService"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(64, 160),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["MemoryStoreDistributedCounter"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["MemoryStoreHashMap"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["MemoryStoreHashMapPages"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["MemoryStoreQueue"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["MemoryStoreService"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(160, 112),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["MemoryStoreSortedMap"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["MeshContentProvider"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["MeshPart"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(176, 112),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["Message"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["MessagingService"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(192, 112),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["MicroProfilerService"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(64, 160),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["Model"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 112),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["ModerationService"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(64, 160),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["ModuleScript"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(224, 112),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["Motor"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["Motor6D"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(240, 112),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["MotorFeature"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["Mouse"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["MouseService"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(64, 160),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["NegateOperation"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(256, 112),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["NetworkMarker"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["NetworkPeer"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["NetworkReplicator"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["NoCollisionConstraint"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(0, 128),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["NotificationService"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(64, 160),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["NumberPose"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["NumberValue"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(160, 224),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["Object"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["ObjectValue"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(160, 224),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["OpenCloudApiV1"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["OpenCloudService"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(64, 160),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["OperationGraph"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["OrderedDataStore"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["OutfitPages"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["PVAdornment"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["PVInstance"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["PackageLink"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(16, 128),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["PackageService"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(64, 160),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["Packages"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["Pages"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["Pants"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(32, 128),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["Part"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(48, 128),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["PartAdornment"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["PartOperation"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["PartOperationAsset"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["ParticleEmitter"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(64, 128),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["PatchBundlerFileWatch"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["PatchMapping"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["Path"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["Path2D"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(80, 128),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["Path3D"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["PathfindingLink"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(96, 128),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["PathfindingModifier"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(112, 128),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["PathfindingService"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(128, 128),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["PermissionsService"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(64, 160),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["PhysicsService"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(64, 160),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["PitchShiftSoundEffect"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(144, 128),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["PlacesService"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(64, 160),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["Plane"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(160, 128),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["PlaneConstraint"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(176, 128),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["Platform"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["PlayerControlState"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(192, 128),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["PlayerData"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["PlayerDataRecord"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["PlayerDataRecordConfig"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["PlayerDataService"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(64, 160),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["PlayerGui"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["PlayerListConfiguration"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["PlayerMouse"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["PlayerScripts"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["PlayerViewService"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(64, 160),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["Players"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 128),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["PluginManagementService"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(64, 160),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["PointLight"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(224, 128),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["PointsService"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(64, 160),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["PolicyService"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(64, 160),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["PopLatencyService"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(64, 160),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["Pose"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["PoseBase"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["PostEffect"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["Preloaded"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["PrismaticConstraint"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(240, 128),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["ProceduralModel"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(256, 128),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["ProcessInstancePhysicsService"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(64, 160),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["ProximityPrompt"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(0, 144),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["ProximityPromptService"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(64, 160),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["PublishService"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(16, 144),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["PyramidHandleAdornment"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["RayValue"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(160, 224),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["RecommendationPages"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["RecommendationService"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(64, 160),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["ReflectionMetadata"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["ReflectionMetadataCallbacks"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["ReflectionMetadataClass"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["ReflectionMetadataClasses"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["ReflectionMetadataEnum"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["ReflectionMetadataEnumItem"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["ReflectionMetadataEnums"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["ReflectionMetadataEvents"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["ReflectionMetadataFunctions"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["ReflectionMetadataItem"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["ReflectionMetadataMember"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["ReflectionMetadataProperties"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["ReflectionMetadataYieldFunctions"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["ReflectionService"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(64, 160),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["RemoteCommandService"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(64, 160),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["RemoteDebuggerServer"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["RemoteEvent"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(32, 144),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["RemoteFunction"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(48, 144),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["RenderingTest"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(64, 144),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["ReplicatedFirst"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(80, 144),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["ReplicatedStorage"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(96, 144),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["ReverbSoundEffect"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(112, 144),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["RigidConstraint"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(128, 144),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["RocketPropulsion"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(144, 144),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["RodConstraint"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(160, 144),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["RopeConstraint"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(176, 144),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["Rotate"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(192, 144),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["RotateP"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["RotateV"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["RotationCurve"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["RunService"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(64, 160),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["RunningAverageItemDouble"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["RunningAverageItemInt"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["RunningAverageTimeIntervalItem"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["SceneAnalysisService"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(64, 160),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["ScreenGui"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 144),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["ScreenshotCapture"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["ScreenshotHud"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["Script"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(224, 144),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["ScriptBuilder"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["ScriptContext"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["ScriptProfilerService"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(64, 160),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["ScriptService"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(64, 160),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["ScrollingFrame"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(240, 144),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["Seat"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(256, 144),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["Selection"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["SelectionBox"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(0, 160),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["SelectionHighlightManager"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["SelectionLasso"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["SelectionPartLasso"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["SelectionPointLasso"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["SelectionSphere"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(16, 160),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["SelfViewConfiguration"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["SensorBase"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["ServerReplicator"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["ServerScriptService"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(32, 160),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["ServerStorage"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(48, 160),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["ServiceProvider"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["ServiceVisibilityService"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(64, 160),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["SessionCheckService"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(64, 160),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["SharedTableRegistry"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["Shirt"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(80, 160),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["ShirtGraphic"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(96, 160),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["SkateboardController"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["SkateboardPlatform"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["Skin"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["Sky"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(112, 160),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["SlidingBallConstraint"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["SlimContentProvider"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["Smoke"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(128, 160),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["Snap"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(144, 160),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["SocialService"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(160, 160),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["SolidModelContentProvider"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["Sound"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(176, 160),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["SoundEffect"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(192, 160),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["SoundGroup"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 160),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["SoundService"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(224, 160),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["Sparkles"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(240, 160),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["SpawnLocation"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(256, 160),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["SpawnerService"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(64, 160),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["SpecialMesh"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(0, 176),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["SphereHandleAdornment"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(16, 176),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["SpotLight"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(32, 176),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["SpringConstraint"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(48, 176),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["StandardPages"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["StarterCharacterScripts"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(64, 176),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["StarterGear"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["StarterGui"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(80, 176),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["StarterPack"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(96, 176),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["StarterPlayer"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(112, 176),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["StarterPlayerScripts"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(128, 176),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["StartupMessageService"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(64, 160),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["Stats"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["StatsItem"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["Status"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["StopWatchReporter"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["StringValue"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(160, 224),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["StudioTestService"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(64, 160),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["StudioTheme"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["StyleBase"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["StyleDerive"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(144, 176),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["StyleLink"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(160, 176),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["StyleQuery"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(176, 176),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["StyleRule"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(192, 176),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["StyleSheet"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 176),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["StylingService"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(64, 160),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["SunRaysEffect"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(224, 176),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["SurfaceAppearance"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(240, 176),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["SurfaceGui"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(256, 176),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["SurfaceGuiBase"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["SurfaceLight"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(0, 192),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["SurfaceSelection"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(16, 192),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["SwimController"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(32, 192),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["SyncScriptBuilder"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["Team"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(48, 192),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["Teams"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(64, 192),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["TeleportAsyncResult"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["TeleportOptions"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["TeleportService"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(64, 160),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["Terrain"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(80, 192),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["TerrainDetail"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(96, 192),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["TerrainIterateOperation"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["TerrainModifyOperation"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["TerrainReadOperation"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["TerrainRegion"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["TerrainWriteOperation"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["TestCase"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["TestService"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(112, 192),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["TextBox"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(128, 192),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["TextBoxService"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(144, 192),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["TextButton"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(160, 192),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["TextChannel"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(176, 192),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["TextChannelWindow"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(192, 192),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["TextChatCommand"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 192),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["TextChatConfigurations"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["TextChatMessage"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["TextChatMessageProperties"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["TextChatService"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(224, 192),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["TextFilterResult"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["TextFilterTranslatedResult"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["TextGenerator"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["TextLabel"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(240, 192),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["TextService"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(64, 160),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["TextSource"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["Texture"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(256, 192),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["TimerService"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(64, 160),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["Tool"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(0, 208),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["Torque"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(16, 208),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["TorsionSpringConstraint"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(32, 208),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["TotalCountTimeIntervalItem"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["TouchInputService"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(64, 160),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["TouchTransmitter"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["TraceRouteService"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(64, 160),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["Trail"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(48, 208),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["Translator"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["TremoloSoundEffect"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(64, 208),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["TriangleMeshPart"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["TrussPart"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(80, 208),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["Tween"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["TweenBase"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["TweenService"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(64, 160),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["UGCValidationService"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(96, 208),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["UIAspectRatioConstraint"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(112, 208),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["UIBase"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["UIComponent"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["UIConstraint"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["UICorner"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(128, 208),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["UIDragDetector"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(144, 208),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["UIDragDetectorService"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(64, 160),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["UIFlexItem"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(160, 208),
        ImageRectSize = Vector2.new(16, 15),
    },

    ["UIGradient"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(176, 208),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["UIGridLayout"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(192, 208),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["UIGridStyleLayout"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["UILayout"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["UIListLayout"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 208),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["UIPadding"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(224, 208),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["UIPageLayout"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(240, 208),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["UIScale"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(256, 208),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["UIShadow"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(0, 224),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["UISizeConstraint"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(16, 224),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["UIStroke"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(32, 224),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["UITableLayout"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(48, 224),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["UITextSizeConstraint"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(64, 224),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["UnionOperation"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(80, 224),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["UniqueIdLookupService"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(64, 160),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["UniversalConstraint"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(96, 224),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["UnreliableRemoteEvent"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(112, 224),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["UserInputService"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(64, 160),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["UserService"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(128, 224),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["VRService"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(144, 224),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["VRStatusService"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(64, 160),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["ValueBase"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["ValueCurve"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["Vector3Curve"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["Vector3Value"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(160, 224),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["VectorForce"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(176, 224),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["VehicleController"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["VehicleSeat"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(192, 224),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["VelocityMotor"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["VideoCapture"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["VideoCaptureService"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(64, 160),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["VideoDisplay"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 224),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["VideoFrame"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(224, 224),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["VideoPlayer"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(240, 224),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["VideoSampler"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["VideoScreenCaptureService"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(64, 160),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["VideoService"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(64, 160),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["ViewportCamera"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["ViewportFrame"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(256, 224),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["VirtualInput"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["VirtualInputManager"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["VirtualUser"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(0, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["VisibilityCheckDispatcher"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["Visit"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["VisualizationMode"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["VisualizationModeCategory"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["VisualizationModeService"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(64, 160),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["VoiceChatInternal"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["VoiceChatService"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(16, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["WebStreamClient"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["WedgePart"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(32, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["Weld"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(48, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["WeldConstraint"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(64, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["Wire"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(80, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["WireframeHandleAdornment"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(96, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["Workspace"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(112, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["WorkspaceAnnotation"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["WorldModel"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(128, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["WorldRoot"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(208, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["WrapDeformer"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(144, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["WrapLayer"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(160, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["WrapTarget"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(176, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

    ["WrapTextureTransfer"] = {
        Image = "rbxassetid://134410168627682",
        ImageRectOffset = Vector2.new(192, 240),
        ImageRectSize = Vector2.new(16, 16),
    },

}
